language: node_js

services:
  - docker

before_install:
  - docker pull amazon/dynamodb-local

node_js:
  - stable

install:
  - npm install

script:
  - npm test

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"